### PR TITLE
New recipe: hg19 phastCons

### PR DESCRIPTION
**Pull request by saketkc**
- [x] Before creating a pull-request please run `ggd check-recipe path/to/recipe-dir/`.

- [ ] If your pull-request errors on travis-ci, follow the link and read the log carefully;
it should give information about what went wrong.

### CODE REVIEW

**Comment by saketkc** [comment]
`ggd check-recipe` succeeds locally. I am not sure I understand what's going on with travis though.

**Comment by saketkc** [comment]
@brentp Any clue what's going wrong here?

**Comment by brentp** [comment]
Thanks for pinging me. I'll have a look at this tomorrow. As you can tell we're in early stages, but I'm still wresting with conda in some cases.

**Comment by brentp** [comment]
I fixed the issue in ggd-cli, but now the command is timing out.

**Comment by saketkc** [comment]
Builds now.

**Comment by saketkc** [comment]
@brentp Thanks the fix!

**Comment by saketkc** [comment]
Hi @brentp, is this good to merge? I am working on a project around this and other few related recipes.

**Comment by brentp** [comment]
merged. thanks for the remdinder.

**Pull request merged**
